Added usage command and cleaned up comments

diff --git a/scripts/ood_scripts/deploy_biocontainer b/scripts/ood_scripts/deploy_biocontainer
--- a/scripts/ood_scripts/deploy_biocontainer
+++ b/scripts/ood_scripts/deploy_biocontainer
@@ -1,4 +1,50 @@
 #!/bin/bash
+# ----------------------------------------------------------------------
+# deploy_biocontainer - Create Open OnDemand application directory for
+#                       given Biocontainer image
+#
+# By Ryan DeRue <rderue@purdue.edu>, 2022
+#
+# ----------------------------------------------------------------------
+
+
+# ----------------------------------------------------------------------
+# Defined Exit Codes
+# ----------------------------------------------------------------------
+
+SUCCESS=0
+ERROR=1
+COMMAND_FORMATTING=2
+
+
+#-----------------------------------------------------------------------
+# Print Usage Information
+#-----------------------------------------------------------------------
+
+usage(){
+cat << 'EOF'
+
+deploy_biocontainer: Create Open OnDemand application directory for a given Biocontainer image 
+
+Usage: deploy_biocontainer 
+
+Options:
+    [-n | --name <name>]: Name to display on Open OnDemand Interface 
+    [-d | --directory <directory>]: Name to give application directory
+    [-c | --command <invocation_command>]: Command to start application
+    [-t | --template <template_directory>]: Path to OoD template directory
+    [-i | --image | -f | --file <version_file>]: YAML formatted options for
+    multiple versions/images OR path to a single image file.
+
+Example:
+   ./deploy_biocontainer --name "scRNAseq RStudio" --directory bio_rstudio_scrnaseq --command rstudio --template ~/ood_app_templates/default_biocontainer_template_anvil/ --file ~/ood_app_templates/app_files/scrnaseq_rstudio_versions.yml 
+EOF
+
+}
+
+#-----------------------------------------------------------------------
+# Fetch Command line Arguments
+#-----------------------------------------------------------------------
 
 POSITIONAL_ARGS=()
 
@@ -34,9 +80,13 @@ while [[ $# -gt 0 ]]; do
       shift
       shift
       ;;
+    -h|--help)
+      usage
+      exit $SUCCESS
+      ;;
     -*|--*)
       echo "Unknown option $1"
-      exit 1
+      exit $COMMAND_FORMATTING 
       ;;
     *)
       POSITIONAL_ARGS+=("$1") # save positional arg
@@ -45,25 +95,27 @@ while [[ $# -gt 0 ]]; do
   esac
 done
 
-#Standard Input validation
+# ----------------------------------------------------------------------
+# Standard Input validation
+# ----------------------------------------------------------------------
 if [[ -z "$NAME" ]]; then
     echo "You need to provide a name for the application. Exiting..."
-    exit 1
+    exit $COMMAND_FORMATTING
 fi
 
 if [[ -z "$IMAGE" && -z "$FILE" ]]; then
     echo "You need to provide an image for the application either as an option or in an input file. Exiting..."
-    exit 1
+    exit $COMMAND_FORMATTING 
 fi
 
 if [[ -z "$COMMAND" ]]; then
     echo "You need to provide the command to start the application. Exiting..."
-    exit 1
+    exit $COMMAND_FORMATTING
 fi
 
 if [[ -z "$TEMPLATE" ]]; then
     echo "You need to provide the path to the template application. Exiting..."
-    exit 1
+    exit $COMMAND_FORMATTING
 fi
 
 if [[ -z "$DIRECTORY" ]]; then
@@ -80,33 +132,49 @@ else
     VERSION_MAP=$(cat "$FILE")
 fi
 
-#Copy template application to new directory
+# ----------------------------------------------------------------------
+# Perform Sanity Check 
+# ----------------------------------------------------------------------
+if [[ -d $DIRECTORY ]]; then
+    echo "$DIRECTORY already exists. Bailing out..."
+    exit $ERROR
+fi
+
+# ----------------------------------------------------------------------
+# Copy Template Application to New Directory
+# ----------------------------------------------------------------------
 cp -r $TEMPLATE $DIRECTORY
 
 for file in form.yml.erb manifest.yml submit.yml.erb template/desktops/xfce.sh
 do
-    #Adjust file
+# ----------------------------------------------------------------------
+# Perform Basic Substitutions with sed
+# ----------------------------------------------------------------------
     sed -i -e "s@GENERICNAME@$NAME@g" -e "s@GENERICIMAGE@$IMAGE@g" -e "s@GENERICDIRECTORY@$DIRECTORY@g" -e "s@GENERICCOMMAND@$COMMAND@g" -e "s@MULTIPLE_VERSIONS_FLAG@$HAS_MULTIPLE_VERSIONS@g" "$DIRECTORY/$file"
 done 
 
-
+# ----------------------------------------------------------------------
+# Format Version Options with awk
+#
+# The below code substitutes the version options from the supplied file with correct indentations for YAML formatting into the form.yml.erb.
+# In a more readable format:
+# function create_version_string()
+# {
+#     version_string=""
+#     while (( getline l < "version_file") > 0 ) {
+#         version_string= version_string "      " l "\n"
+#         }
+#     return version_string
+#    
+#
+# } 
+# BEGIN { version_map=create_version_string() }
+# { gsub(/VERSION_OPTIONS/, version_map); print }
+# ----------------------------------------------------------------------
 if [[ -z "$FILE" ]]; then 
     sed -i -e "s@VERSION_OPTIONS@      $DUMMY_FILE@g" "$DIRECTORY/form.yml.erb"
 else
-#The below line substitutes the version options from the supplied file with correct indentations for YAML formatting into the form.yml.erb.
-#In a more readable format:
-#Build the correctly indented YAML syntax for version selection
-#function create_version_string()
-#{
-#    version_string=""
-#    while (( getline l < "version_file") > 0 ) {
-#        version_string= version_string "      " l "\n"
-#        }
-#    return version_string
-#    
-#
-#} 
-#BEGIN { version_map=create_version_string() }
-#{ gsub(/VERSION_OPTIONS/, version_map); print }
     awk -v file=$FILE 'function create_version_string(){ while ((getline l < file) > 0 ) { version_string=version_string "      " l "\n" } return version_string } BEGIN { version_map=create_version_string() } { gsub(/VERSION_OPTIONS/, version_map); print }' < $DIRECTORY/form.yml.erb > tmp && mv tmp $DIRECTORY/form.yml.erb
 fi 
+
+exit $SUCCESS
